apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dep
  labels:
    app: services-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services-broker
  template:
    metadata:
      labels:
        app: services-broker
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
      containers:
        - name: services-broker-container
          image: rabbitmq:management-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /var/lib/rabbitmq
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  selector:
    app: services-broker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
