apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-private-key: M2M0MGIxMDE5OTY1M2NhYjhiNDFjOTFjMzRmYjAyNzk2NGQyZDU2MjhiYzJlNjE0MTc0NjQ5Y2MzNDhhNGE5MWZhYmU5MmUxM2YyYjg2Y2ZiZDExMDMwYTFjODlhOTY5OTUwZjQ4YTlhNGYzZjA4MjY1YTdjYzRjYTZkYjc3MTA=
