apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activation-service-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activation-service-redis-dep
  labels:
    app: activation-service-redis
spec:
  selector:
    matchLabels:
      app: activation-service-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: activation-service-redis
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: activation-service-redis-pvc
      containers:
        - name: activation-service-redis-container
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /data
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: activation-service-redis-svc
  labels:
    app: activation-service-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: activation-service-redis
