apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-service-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-database-dep
  labels:
    app: post-service-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service-database
  template:
    metadata:
      labels:
        app: post-service-database
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: post-service-database-pvc
      containers:
        - name: post-service-database-container
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-database-svc
spec:
  selector:
    app: post-service-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
