export enum Governorate {
	Damascus = "Damascus",
	Raqqa = "Raqqa",
	Suweyda = "Suweyda",
	Daraa = "Daraa",
	DeirElZor = "Deir El-Zor",
	Hama = "Hama",
	Hasaka = "Hasaka",
	Homs = "Homs",
	Idlib = "Idlib",
	Latakia = "Latakia",
	Tartus = "Tartus",
}
export const Governorates = [
	Governorate.Damascus,
	Governorate.Raqqa,
	Governorate.Suweyda,
	Governorate.Daraa,
	Governorate.DeirElZor,
	Governorate.Hama,
	Governorate.Hasaka,
	Governorate.Homs,
	Governorate.Idlib,
	Governorate.Latakia,
	Governorate.Tartus,
];
