apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-dep
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app-container
          image: jadhamwi21/jobseekingsy:v1-nginx-react-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-svc
spec:
  type: NodePort
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

